server:
  port: 8081

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: municipios-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: municipios-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5433/db_municipios
    username: user_municipios
    password: pwd_municipios
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect