FROM jenkins/jenkins:lts-jdk17

USER root
RUN apt-get update && apt-get install -y docker.io && rm -rf /var/lib/apt/lists/*

USER jenkins
# Copia a lista de plugins e instala-os
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN jenkins-plugin-cli --plugins -f /usr/share/jenkins/ref/plugins.txt

# 🎯 INJECTAR A CONFIGURAÇÃO AS CODE
COPY jenkins.yaml /var/jenkins_config/jenkins.yaml
ENV CASC_JENKINS_CONFIG=/var/jenkins_config/jenkins.yaml