server:
  port: 8082

spring:
  application:
    name: mercados-service
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 50MB
  sql:
    init:
      mode: always
  # Base de dados unificada de feiras e candidaturas
  datasource:
    url: jdbc:postgresql://localhost:5434/db_mercados
    username: user_mercados
    password: pwd_mercados

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Escuta o tópico 'feirante-registado-topic' vindo do identidade-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: mercados-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
  data:
    web:
      pageable:
        page-serialization-mode: via-dto